language: shell
os: linux
dist: bionic
services:
  - docker

notifications:
  email: false

jobs:
  include:
    - env: BUNGEECORD_JOB_ID=lastStableBuild
    - if: branch = master
      env: BUNGEECORD_JOB_ID=1119 # 1.7.10
    - if: branch = master
      env: BUNGEECORD_JOB_ID=701 # 1.6.4
    - if: branch = master
      env: BUNGEECORD_JOB_ID=666 # 1.6.2
    - if: branch = master
      env: BUNGEECORD_JOB_ID=548 # 1.5.2
    - if: branch = master
      env: BUNGEECORD_JOB_ID=386 # 1.5.0
    - if: branch = master
      env: BUNGEECORD_JOB_ID=251 # 1.4.7

script:
  - ./build/travis.sh
