os: linux
dist: bionic
language: minimal
services:
  - docker

notifications:
  email: false

jobs:
  include:
    - env: BUNGEECORD_JOB_ID=lastStableBuild
    - env: BUNGEECORD_JOB_ID=1119 # 1.7.10
    - env: BUNGEECORD_JOB_ID=701 # 1.6.4
    - env: BUNGEECORD_JOB_ID=666 # 1.6.2
    - env: BUNGEECORD_JOB_ID=548 # 1.5.2
    - env: BUNGEECORD_JOB_ID=386 # 1.5.0
    - env: BUNGEECORD_JOB_ID=251 # 1.4.7

before_install:
  - chmod +x docker_push.sh

script:
  - ./docker_push.sh
